package nextstep.courses.infrastructure.persistence.dao;

import java.time.LocalDateTime;
import java.util.Optional;
import nextstep.courses.infrastructure.persistence.entity.ImageEntity;
import org.springframework.jdbc.core.JdbcOperations;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

@Repository("imageEntityRepository")
public class ImageEntityRepository {

  private final JdbcOperations jdbcTemplate;

  public ImageEntityRepository(JdbcOperations jdbcTemplate) {
    this.jdbcTemplate = jdbcTemplate;
  }

  /**
   *  create table image (
   *     id bigint generated by default as identity,
   *     original_file_name varchar(255) not null,
   *     image_type varchar(20) not null,
   *     cover_img_url varchar(255) not null,
   *     primary key (id)
   * );
   */
  public Optional<ImageEntity> findById(Long coverImageId) {
    String sql = "select id, original_file_name, image_type, cover_img_url, created_at, updated_at from image where id = ?";
    return jdbcTemplate.queryForObject(sql, rowMapper(), coverImageId);
  }

  private RowMapper<Optional<ImageEntity>> rowMapper() {
    return (rs, rowNum) -> {
      Long id = rs.getLong("id");
      String originalFileName = rs.getString("original_file_name");
      String imageType = rs.getString("image_type");
      String coverImgUrl = rs.getString("cover_img_url");
      LocalDateTime createdAt = rs.getTimestamp("created_at").toLocalDateTime();
      LocalDateTime updatedAt = rs.getTimestamp("updated_at").toLocalDateTime();

      return Optional.of(
          new ImageEntity(id, originalFileName, imageType, coverImgUrl, createdAt, updatedAt));
    };
  }
}
