INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (2, 'sanjigi', 'Car1q2w3e4r5t!', '산지기', 'sanjigi@slipp.com', CURRENT_TIMESTAMP());

INSERT INTO question (id, writer_id, title, contents, created_at, deleted) VALUES (1, 1, '국내에서 Ruby on Rails와 Play가 활성화되기 힘든 이유는 뭘까?', 'Ruby on Rails(이하 RoR)는 2006년 즈음에 정말 뜨겁게 달아올랐다가 금방 가라 앉았다. Play 프레임워크는 정말 한 순간 잠시 눈에 뜨이다가 사라져 버렸다. RoR과 Play 기반으로 개발을 해보면 정말 생산성이 높으며, 웹 프로그래밍이 재미있기까지 하다. Spring MVC + JPA(Hibernate) 기반으로 진행하면 설정할 부분도 많고, 기본으로 지원하지 않는 기능도 많아 RoR과 Play에서 기본적으로 지원하는 기능을 서비스하려면 추가적인 개발이 필요하다.', CURRENT_TIMESTAMP(), false);

INSERT INTO answer (writer_id, contents, created_at, question_id, deleted) VALUES (1, 'http://underscorejs.org/docs/underscore.html Underscore.js 강추합니다! 쓸일도 많고, 코드도 길지 않고, 자바스크립트의 언어나 기본 API를 보완하는 기능들이라 자바스크립트 이해에 도움이 됩니다. 무엇보다 라이브러리 자체가 아주 유용합니다.', CURRENT_TIMESTAMP(), 1, false);

INSERT INTO answer (writer_id, contents, created_at, question_id, deleted) VALUES (2, '언더스코어 강력 추천드려요. 다만 최신 버전을 공부하는 것보다는 0.10.0 버전부터 보는게 더 좋더군요. 코드의 변천사도 알 수 있고, 최적화되지 않은 코드들이 기능은 그대로 두고 최적화되어 가는 걸 보면 재미가 있습니다 :)', CURRENT_TIMESTAMP(), 1, false);

INSERT INTO question (id, writer_id, title, contents, created_at, deleted) VALUES (2, 2, 'runtime 에 reflect 발동 주체 객체가 뭔지 알 방법이 있을까요?', '설계를 희한하게 하는 바람에 꼬인 문제같긴 합니다만. 여쭙습니다. 상황은 mybatis select 실행될 시에 return object 의 getter 가 호출되면서인데요. getter 안에 다른 property 에 의존중인 코드가 삽입되어 있어서, 만약 다른 mybatis select 구문에 해당 property 가 없다면 exception 이 발생하게 됩니다.', CURRENT_TIMESTAMP(), false);


insert into session (id, title, free, created_at, imgFile, started_at, ended_at, status) values(1,'테스트중입니다', true, now(), 'test.jpg', DATEADD('DAY', 8, CURRENT_TIMESTAMP()), DATEADD('DAY', 14, CURRENT_TIMESTAMP()), 'RECRUITING');
insert into session (id, title, free, created_at, imgFile, started_at, ended_at, status) values(2,'테스트중입니다', true, now(), 'test.jpg', DATEADD('DAY', 8, CURRENT_TIMESTAMP()), DATEADD('DAY', 14, CURRENT_TIMESTAMP()), 'RECRUITING');


insert into session_user_mapping (id, session_id, ns_user_id, created_at) values(1, 1, 1, now());
insert into session_user_mapping (id, session_id, ns_user_id, created_at) values(2, 1, 2, now());
insert into session_user_mapping (id, session_id, ns_user_id, created_at) values(3, 1, 3, now());
insert into session_user_mapping (id, session_id, ns_user_id, created_at) values(4, 1, 4, now());
insert into session_user_mapping (id, session_id, ns_user_id, created_at) values(5, 1, 5, now());



INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1001, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1002, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1003, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1004, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1005, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1006, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1007, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1008, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1009, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1010, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1011, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1012, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1013, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1014, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1015, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1016, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1017, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1018, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1019, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1020, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1021, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1022, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1023, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1024, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1025, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1026, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1027, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1028, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1029, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1030, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1031, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1032, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1033, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1034, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1035, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1036, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1037, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1038, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1039, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1040, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1041, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1042, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1043, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1044, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1045, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1046, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1047, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1048, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1049, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1050, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1051, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1052, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1053, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1054, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1055, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1056, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1057, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1058, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1059, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1060, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1061, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1062, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1063, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1064, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1065, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1066, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1067, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1068, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1069, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1070, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1071, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1072, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1073, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1074, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1075, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1076, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1077, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1078, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1079, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1080, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1081, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1082, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1083, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1084, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1085, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1086, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1087, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1088, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1089, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1090, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1091, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1092, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1093, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1094, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1095, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1096, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1097, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1098, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1099, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1100, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1101, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1102, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1103, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1104, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1105, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1106, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1107, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1108, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1109, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1110, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1111, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1112, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1113, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1114, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1115, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());
INSERT INTO ns_user (id, user_id, password, name, email, created_at) values (1116, 'javajigi', 'Car1q2w3e4r5t!', '자바지기', 'javajigi@slipp.com', CURRENT_TIMESTAMP());

