create table course (
    id bigint generated by default as identity,
    title varchar(255) not null,
    creator_id bigint not null,
    cohort bigint not null,
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table ns_user (
    id bigint generated by default as identity,
    user_id varchar(20) not null,
    password varchar(20) not null,
    name varchar(20) not null,
    email varchar(50),
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table question (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    title varchar(100) not null,
    writer_id bigint,
    primary key (id)
);

create table answer (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    question_id bigint,
    writer_id bigint,
    primary key (id)
);

create table delete_history (
    id bigint not null,
    content_id bigint,
    content_type varchar(255),
    created_date timestamp,
    deleted_by_id bigint,
    primary key (id)
);

create table session (
    id bigint generated by default as identity,
    name varchar(20) not null,
    start_date DATE not null,
    end_date DATE not null,
    cover_image varchar(255),
    payment_type varchar(10) default 'FREE',
    status varchar(10) default 'READY',
    enrollment varchar(20) default 'ENROLLMENT',
    registered_student bigint default 0,
    max_student bigint default 30,
    course_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    PRIMARY KEY (id),
    FOREIGN KEY (course_id) REFERENCES course (id)
);

