package nextstep.courses.infrastructure.persistence.entity;

import java.time.LocalDateTime;
import nextstep.courses.domain.BaseTimeEntity;
import nextstep.users.domain.NsUser;
import nextstep.users.infrastructure.entity.NsUserEntity;

/**
 * JPA 처럼 ENtity를 구성한다.
 *
 *
   create table course (
   id bigint generated by default as identity,
   title varchar(255) not null,
   creator_id bigint not null,
   generation varchar(20) not null,
   created_at timestamp not null,
   updated_at timestamp,
   primary key (id),
   FOREIGN KEY (creator_id) REFERENCES ns_user (id)
   );
 */
public class CourseEntity extends BaseTimeEntity {

  private Long id;

  private String title;

  private NsUserEntity creator;

  private String generation;

  public CourseEntity() {
  }

  /**
   * 주 생성자
   */
  public CourseEntity(String title, NsUserEntity creator, String generation, LocalDateTime createdAt, LocalDateTime updatedAt) {
    super(createdAt, updatedAt);
    this.title = title;
    this.creator = creator;
    this.generation = generation;
  }



}
