package nextstep.courses.infrastructure.persistence.entity;

import java.time.LocalDateTime;
import nextstep.courses.domain.BaseTimeEntity;
import nextstep.courses.domain.Course;

/**
 * JPA 처럼 ENtity를 구성한다.
 *
 *
   create table course (
   id bigint generated by default as identity,
   title varchar(255) not null,
   creator_id bigint not null,
   generation varchar(20) not null,
   created_at timestamp not null,
   updated_at timestamp,
   primary key (id),
   FOREIGN KEY (creator_id) REFERENCES ns_user (id)
   );
 */
public class CourseEntity extends BaseTimeEntity {

  private Long id;

  private String title;

  private Long creatorId;

  private String generation;

  public CourseEntity() {
  }

  /**
   * 주 생성자
   */
  public CourseEntity(long id, String title, Long creatorId, String generation,
      LocalDateTime createdAt, LocalDateTime updatedAt) {
    super(createdAt, updatedAt);
    this.id = id;
    this.title = title;
    this.creatorId = creatorId;
    this.generation = generation;
  }

  public Long getId() {
    return id;
  }

  public String getTitle() {
    return title;
  }

  public Long getCreatorId() {
    return creatorId;
  }

  public String getGeneration() {
    return generation;
  }

  public LocalDateTime getCreatedAt() {
    return createdAt;
  }

  public Course toDomain() {
    return new Course(id, title, creatorId, generation, createdAt, updatedAt);
  }
}
