package nextstep.courses.infrastructure.persistence.entity;

import java.time.LocalDateTime;
import nextstep.courses.domain.BaseTimeEntity;
import nextstep.courses.domain.ImageType;
import nextstep.courses.domain.Url;

/**
 *  create table image (
 *     id bigint generated by default as identity,
 *     original_file_name varchar(255) not null,
 *     image_type varchar(20) not null,
 *     cover_img_url varchar(255) not null,
 *     primary key (id)
 * );
 */
public class ImageEntity extends BaseTimeEntity {

  private Long id;

  private String originalFileName;

  private ImageType imageType;

  private Url coverImgUrl;

  public ImageEntity() {
  }

  /**
   * 주 생성자
   */
  public ImageEntity(String originalFileName, ImageType imageType, Url coverImgUrl, LocalDateTime createdAt, LocalDateTime updatedAt) {
    super(createdAt, updatedAt);
    this.originalFileName = originalFileName;
    this.imageType = imageType;
    this.coverImgUrl = coverImgUrl;
  }


}
