package nextstep.courses.infrastructure.persistence.entity;

import java.time.LocalDateTime;
import nextstep.courses.domain.BaseTimeEntity;
import nextstep.courses.domain.Image;
import nextstep.courses.domain.ImageType;
import nextstep.courses.domain.Url;

/**
 *  create table image (
 *     id bigint generated by default as identity,
 *     original_file_name varchar(255) not null,
 *     image_type varchar(20) not null,
 *     cover_img_url varchar(255) not null,
 *     primary key (id)
 * );
 */
public class ImageEntity extends BaseTimeEntity {

  private Long id;

  private String originalFileName;

  private ImageType imageType;

  private Url coverImgUrl;

  public ImageEntity() {
  }

  /**
   * 주 생성자
   */
  public ImageEntity(Long id, String originalFileName, ImageType imageType, Url coverImgUrl, LocalDateTime createdAt, LocalDateTime updatedAt) {
    super(createdAt, updatedAt);
    this.id = id;
    this.originalFileName = originalFileName;
    this.imageType = imageType;
    this.coverImgUrl = coverImgUrl;
  }


  public ImageEntity(Long id, String originalFileName, String imageType, String coverImgUrl,
      LocalDateTime createdAt, LocalDateTime updatedAt) {
    this(id, originalFileName, ImageType.valueOf(imageType), new Url(coverImgUrl), createdAt, updatedAt);
  }


  public Image toDomain() {
    return new Image(id, originalFileName, imageType, coverImgUrl);
  }


  public Long getId() {
    return id;
  }

  public String getOriginalFileName() {
    return originalFileName;
  }

  public ImageType getImageType() {
    return imageType;
  }

  public Url getCoverImgUrl() {
    return coverImgUrl;
  }
}
