package nextstep.courses.infrastructure.persistence.entity;

import nextstep.courses.domain.BaseTimeEntity;
import nextstep.users.infrastructure.entity.NsUserEntity;

/**
 * JPA 처럼 구상한다.
 * Session 과 Student 사이의 중간 테이블
 *  create table session_enrollment (
 *     id bigint generated by default as identity,
 *     session_id bigint not null,
 *     user_id bigint not null,
 *     created_at timestamp not null,
 *     updated_at timestamp,
 *     primary key (id),
 *     foreign key (session_id) references session(id),
 *     foreign key (user_id) references ns_user(id)
 * );
 */
public class SessionEnrollment extends BaseTimeEntity {

  private Long id;

  private SessionEntity session;

  private NsUserEntity user;





}
