package nextstep.courses.infrastructure.persistence.entity;

import java.time.LocalDateTime;
import nextstep.courses.domain.BaseTimeEntity;

/**
 * JPA 처럼 구상한다.
 * Session 과 Student 사이의 중간 테이블
 *  create table session_enrollment (
 *     id bigint generated by default as identity,
 *     session_id bigint not null,
 *     user_id bigint not null,
 *     created_at timestamp not null,
 *     updated_at timestamp,
 *     primary key (id),
 *     foreign key (session_id) references session(id),
 *     foreign key (user_id) references ns_user(id)
 * );
 */
public class SessionEnrollment extends BaseTimeEntity {

  private Long id;

  private Long sessionId;

  private Long userId;

  public SessionEnrollment() {
  }

  public SessionEnrollment(Long sessionId, Long userId, LocalDateTime createdAt, LocalDateTime updatedAt) {
    super(createdAt, updatedAt);
    this.sessionId = sessionId;
    this.userId = userId;
  }





}
